// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export enum Action {
  SR_INIT_CONSUMER = 0,
  SR_INIT_TRANSPORTS = 1,
  SR_PING = 2,
  SM_BROADCAST = 3,
  SM_SESSION_LEAVE = 4,
  SM_INFO_CHANGE = 5,
  CR_CONNECT_CTS_TRANSPORT = 6,
  CR_CONNECT_STC_TRANSPORT = 7,
  CR_INIT_PRODUCER = 8,
  CM_BROADCAST = 9,
  CM_CONSUMPTION_CHANGE = 10,
  CM_INFO_CHANGE = 11,
  CM_PRODUCER_CHANGE = 12
}
